spring:
  config.activate.on-profile: default
  datasource:
    url: jdbc:mariadb://cat-database.ccmo8onyohgn.ap-northeast-2.rds.amazonaws.com:3306/cat_database
    username: admin
    password: catewha2022
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;;MODE=MySQL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect